using System;

namespace NumberPlateGenerator.Net.Core.Provinces
{
    [Flags]
    public enum DProvinces : int
    {
        Unknown = 0,
        A = 1 << 0, //Augsburg
        ABI = 1 << 1, //Anhalt,//Bitterfeld
        AB = 1 << 2, //Aschaffenburg
        AIC = 1 << 3, //Aichach,//Friedberg
        AS = 1 << 3, //Amberg
        AT = 1 << 4, //Altentreptow
        AÖ = 1 << 5, //Altötting
        B = 1 << 6, //Berlin
        BIT = 1 << 7, //Bitburg,//Prüm
        BIR = 1 << 8, //Birkenfeld
        BN = 1 << 9, //Bonn
        BO = 1 << 10, //Bochum
        BOR = 1 << 11, //Borken
        BRK = 1 << 12, //Landkreis Bad Kissingen
        BT = 1 << 13, //Bayreuth
        BU = 1 << 14, //Burghausen
        BÜZ = 1 << 15, //Bützow
        CE = 1 << 16, //Celle
        C = 1 << 17, //Chemnitz
        COC = 1 << 18, //Cochem,//Zell
        COE = 1 << 19, //Coesfeld
        DA = 1 << 20, //Darmstadt
        DAU = 1 << 21, //Daun
        DN = 1 << 22, //Düren
        DGF = 1 << 23, //Dingolfing,//Landau
        DÜW = 1 << 24, //Bad Dürkheim
        DS = 1 << 25, //Dessau,//Roßlau
        DD = 1 << 26, //Dresden
        E = 1 << 27, //Essen
        EA = 1 << 28, //Ilm,//Kreis
        EBE = 1 << 29, //Ebersberg
        ED = 1 << 30, //Erding
        EDW = 1 << 31, //Elbe,//Weser
        EF = 1 << 32, //Erfurt
        ES = 1 << 33, //Esslingen
        F = 1 << 34, //Frankfurt
        FFB = 1 << 35, //Fürstenfeldbruck
        FF = 1 << 36, //Frankfurt (Oder)
        FRG = 1 << 37, //Freyung,//Grafenau
        FY = 1 << 38, //Friesland (Netherlands)
        G = 1 << 39, //Göttingen
        GER = 1 << 40, //Gerolstein
        GI = 1 << 41, //Gießen
        GTH = 1 << 42, //Gotha
        GÖ = 1 << 43, //Göttingen
        GÖD = 1 << 44, //Görlitz
        H = 1 << 45, //Hanover (Hannover)
        HAM = 1 << 46, //Hamm
        HD = 1 << 47, //Heidelberg
        HIG = 1 << 48, //Werra,//Meißner,//Kreis
        HSK = 1 << 49, //Hochsauerlandkreis
        HX = 1 << 50, //Höxter
        HST = 1 << 51, //Rostock
        IN = 1 << 52, //Ingolstadt
        KA = 1 << 53, //Karlsruhe
        KH = 1 << 54, //Bad Kreuznach
        KL = 1 << 55, //Kaiserslautern
        K = 1 << 56, //Cologne (Köln)
        KLE = 1 << 57, //Kleve
        KIB = 1 << 58, //Kaiserslautern
        KK = 1 << 59, //Kerkrade (Netherlands)
        KM = 1 << 60, //Kamenz
        KO = 1 << 61, //Koblenz
        KÖZ = 1 << 62, //Kötzting
        KP = 1 << 63, //Kempten (Allgäu)
        KUS = 1 << 64, //Kusel
        L = 1 << 65, //Leipzig
        LAI = 1 << 66, //Landau in der Pfalz
        LB = 1 << 67, //Ludwigsburg
        LIP = 1 << 68, //Lippe
        LL = 1 << 69, //Landsberg am Lech
        LU = 1 << 70, //Ludwigshafen
        LUP = 1 << 71, //Ludwigslust,//Parchim
        LS = 1 << 72, //Lüdenscheid
        M = 1 << 73, //Munich (München)
        MA = 1 << 74, //Mannheim
        MEK = 1 << 75, //Saale,//Orla,//Kreis
        MG = 1 << 76, //Mönchengladbach
        MKK = 1 << 77, //Main,//Kinzig,//Kreis
        MTK = 1 << 78, //Main,//Taunus,//Kreis
        MS = 1 << 79, //Münster
        MSE = 1 << 80, //Müritz
        NU = 1 << 81, //Neuburg,//Schrobenhausen
        NVP = 1 << 82, //Neustadt an der Waldnaab
        NWM = 1 << 83, //Nordwestmecklenburg
        NZ = 1 << 84, //Neustrelitz
        OA = 1 << 85, //Garmisch,//Partenkirchen
        OAL = 1 << 86, //Ostallgäu
        OB = 1 << 87, //Oberhausen
        OBG = 1 << 88, //Oberhavel
        OC = 1 << 89, //Oberspreewald,//Lausitz
        OD = 1 << 90, //Oder,//Spree
        OE = 1 << 91, //Olpe
        OF = 1 << 92, //Offenbach am Main
        OG = 1 << 93, //Ortenaukreis
        OH = 1 << 94, //Stormarn (Germany)
        OHA = 1 << 95, //Osterode am Harz
        OHV = 1 << 96, //Oberhavel
        OHZ = 1 << 97, //Osterholz
        OK = 1 << 98, //Saalekreis
        OL = 1 << 99, //Oldenburg (Oldb)
        OP = 1 << 100, //Ober,//Pfalz (Germany)
        OS = 1 << 101, //Osnabrück
        OSL = 1 << 102, //Oberspreewald,//Lausitz
        OVI = 1 << 103, //Ostvorpommern
        OVP = 1 << 104, //Ostvorpommern
        OZ = 1 << 105, //Ludwigslust,//Parchim
        P = 1 << 106, //Potsdam
        PA = 1 << 107, //Passau
        PAF = 1 << 108, //Pfaffenhofen
        PAN = 1 << 109, //Passau
        PB = 1 << 110, //Paderborn
        PCH = 1 << 111, //Ludwigslust,//Parchim
        PE = 1 << 112, //Peine
        PI = 1 << 113, //Starnberg
        PL = 1 << 114, //Potsdam
        PLÖ = 1 << 115, //Ploen
        PM = 1 << 116, //Potsdam,//Mittelmark
        PR = 1 << 117, //Prignitz
        PS = 1 << 118, //Pirmasens
        PW = 1 << 119, //Pw
        R = 1 << 120, //Regensburg
        RA = 1 << 121, //Ravensburg
        RD = 1 << 122, //Rendsburg,//Eckernförde
        RDG = 1 << 123, //Rostock
        RE = 1 << 124, //Recklinghausen
        REG = 1 << 125, //Regen
        REM = 1 << 126, //Rems,//Murr,//Kreis
        RES = 1 << 127, //Augsburg
        RG = 1 << 128, //Rosenheim
        RH = 1 << 129, //Rhein,//Hunsrück,//Kreis
        RHE = 1 << 130, //Rhein,//Erft,//Kreis
        RI = 1 << 131, //Rheinisch,//Bergischer Kreis
        RIE = 1 << 132, //Riesa,//Großenhain
        RO = 1 << 133, //Rosenheim
        ROW = 1 << 134, //Rotenburg (Wümme)
        RPL = 1 << 135, //Rheinland,//Pfalz
        RÜD = 1 << 136, //Marburg,//Biedenkopf
        RÜG = 1 << 137, //Rügen
        RV = 1 << 138, //Ravensburg
        RW = 1 << 139, //Rheinland,//Pfalz
        RZ = 1 << 140, //Rendsburg
        S = 1 << 141, //Stuttgart
        SAD = 1 << 142, //Schwandorf
        SAK = 1 << 143, //Saalekreis
        SAN = 1 << 144, //Wunsiedel im Fichtelgebirge
        SB = 1 << 145, //Saarbrücken
        SBG = 1 << 146, //Saarburg
        SBN = 1 << 147, //Saarburg
        SBÜ = 1 << 148, //Saarburg
        SC = 1 << 149, //Schwarzwald,//Baar,//Kreis
        SDH = 1 << 150, //Suhl
        SE = 1 << 151, //Segeberg
        SEG = 1 << 152, //Stendal
        SEK = 1 << 153, //Salzlandkreis
        SEL = 1 << 154, //Seelow
        SFA = 1 << 155, //Saalfeld,//Rudolstadt
        SG = 1 << 156, //Sangerhausen
        SGH = 1 << 157, //Saalekreis
        SH = 1 << 158, //Schleswig,//Holstein
        SHA = 1 << 159, //Schwäbisch Hall
        SHL = 1 << 160, //Suhl
        SI = 1 << 161, //Siegen
        SIG = 1 << 162, //Sigmaringen
        SIM = 1 << 163, //Simmern
        SL = 1 << 164, //Saarlouis
        SLS = 1 << 165, //Saarlouis
        SLÜ = 1 << 166, //Schleiz
        SM = 1 << 167, //Schmölln
        SN = 1 << 168, //Schwerin
        SO = 1 << 169, //Solingen
        SOK = 1 << 170, //Saale,//Orla,//Kreis
        SON = 1 << 171, //Sonneberg
        SP = 1 << 172, //Speyer
        SPN = 1 << 173, //Spree,//Neiße
        SR = 1 << 174, //Straubing
        SRB = 1 << 175, //Straubing
        SRO = 1 << 176, //Saalfeld,//Rudolstadt
        ST = 1 << 177, //Stendal
        STA = 1 << 178, //Starnberg
        STL = 1 << 179, //Stollberg
        SU = 1 << 180, //Rhein,//Sieg,//Kreis
        SW = 1 << 181, //Schwerin
        SWA = 1 << 182, //Schwabach
        SWK = 1 << 183, //Saale,//Orla,//Kreis
        SWS = 1 << 184, //Saarwellingen
        SY = 1 << 185, //Schmölln
        TBB = 1 << 186, //Main,//Tauber,//Kreis
        TE = 1 << 187, //Tecklenburg
        THL = 1 << 188, //Thuringia
        TIR = 1 << 189, //Tirschenreuth
        TO = 1 << 190, //Torgau
        TÖL = 1 << 191, //Bad Tölz,//Wolfratshausen
        TR = 1 << 192, //Trier
        TUT = 1 << 193, //Tuttlingen
        UE = 1 << 194, //Uelzen
        UER = 1 << 195, //Uecker,//Randow
        UFF = 1 << 196, //Uffenheim
        UG = 1 << 197, //St. Georgen im Schwarzwald
        UL = 1 << 198, //Ulm
        UM = 1 << 199, //Unna
        UN = 1 << 200, //Unna
        USI = 1 << 201, //Usti nad Orlici
        V = 1 << 202, //Vogtlandkreis
        VER = 1 << 203, //Verden
        VG = 1 << 204, //Völklingen
        VIB = 1 << 205, //Vogtlandkreis
        VIE = 1 << 206, //Viersen
        VK = 1 << 207, //Völklingen
        VR = 1 << 208, //Vorpommern,//Rügen
        VW = 1 << 209, //Vilseck
        W = 1 << 210, //Wesel
        WAF = 1 << 211, //Warendorf
        WB = 1 << 212, //Wittenberg
        WBS = 1 << 213, //Wittenberg
        WEN = 1 << 214, //Weiden
        WER = 1 << 215, //Wertingen
        WES = 1 << 216, //Wesel
        WF = 1 << 217, //Wolfenbüttel
        WHV = 1 << 218, //Wilhelmshaven
        WI = 1 << 219, //Wiesbaden
        WK = 1 << 220, //Wittenberg
        WL = 1 << 221, //Ludwigslust,//Parchim
        WM = 1 << 222, //Weilheim
        WND = 1 << 223, //St. Wendel
        WO = 1 << 224, //Wolfenbüttel
        WOB = 1 << 225, //Wolfsburg
        WST = 1 << 226, //Nordwestmecklenburg
        WT = 1 << 227, //Rastatt
        WUG = 1 << 228, //Weißenburg,//Gunzenhausen
        WÜ = 1 << 229, //Würzburg
        WUN = 1 << 230, //Wunsiedel im Fichtelgebirge
        WUR = 1 << 231, //Bad Wurzach
        WW = 1 << 232, //Westerwaldkreis
        WZ = 1 << 233, //Weilheim,//Schongau
        WZL = 1 << 234, //Weilheim,//Schongau
        Z = 1 << 235, //Zwickau
        ZE = 1 << 236, //Zerbst
        ZI = 1 << 237, //Zittau
        ZIG = 1 << 238, //Zittau
        ZP = 1 << 239, //Zschopau
        ZW = 1 << 240, //Zweiwbrücken
    }
}